env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_script:
  - docker-compose up --build -d

script:
  - java -jar cromwell-43.jar submit hello.wdl -h http://localhost:8080

after_script:
  - docker-compose down