sudo: required

services:
  - docker

env:
  golbal:
  - COMPOSE_FILE=docker-compose.yml

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

addons:
  apt:
    packages:
      - docker-ce

script:
  - ls -lah
  - docker-compose up -d --build
  - docker-compose ps
  - docker-compose exec cromwell pwd
  - docker-compose exec cromwell ls
  - docker logs db
  - docker logs cromwell
  - ./test.sh
  
after_script:
  - docker-compose down

notifications:
  email:
    - cb.hong@ngenebio.com