sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2
  - COMPOSE_FILE=docker-compose.yml

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

addons:
  apt:
    packages:
      - docker-ce

script:
  - ls -lah
  - docker-compose up -d --build cromwell
  - docker-compose ps
  - docker-compose exec cromwell ls
  - docker-compose exec cromwell ls /opt/cromwell
  - docker-compose exec cromwell wget --server-response http://localhost:8080/engine/v1/status

  
after_script:
  - docker-compose down

notifications:
  email:
    - cb.hong@ngenebio.com